services:
  api:
    image: nicolaidam/feedback-api:${VERSION}
    container_name: api
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FIREBASE_CONFIG_PATH: ${FIREBASE_CONFIG_PATH}
      LOG_PATH: ${LOG_PATH}
    volumes:
      - logs:${LOG_DIR}
      - ./firebase_config.json:${FIREBASE_CONFIG_PATH}:ro
    ports:
      - "${API_PORT}:8080"
    networks:
      - feedback-network
    restart: unless-stopped

  scheduler:
    image: nicolaidam/feedback-scheduler:${VERSION}
    container_name: scheduler
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FIREBASE_CONFIG_PATH: ${FIREBASE_CONFIG_PATH}
    volumes:
      - logs:${LOG_DIR}
      - ./firebase_config.json:${FIREBASE_CONFIG_PATH}:ro
    networks:
      - feedback-network
    restart: unless-stopped
volumes:
  config:
  logs:

networks:
  feedback-network:
    external: true