name: feedback

services:
  api:
    image: "nicolaidam/feedback-api:prod"
    restart: unless-stopped
    environment:
      PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8090"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
      SPRING_DOC_API_DOCS_ENABLED: "true"
      SPRING_DOC_SWAGGER_UI_ENABLED: "true"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD:-}"
      JWK_SET_URL: "${JWK_SET_URL:-}"
      JWT_ISSUER_URI: "${JWT_ISSUER_URI:-}"
      FIREBASE_API_KEY: "${FIREBASE_API_KEY:-}"
      FIREBASE_CONFIG_PATH: "${FIREBASE_CONFIG_PATH:-}"
      JAVA_OPTS: "${JAVA_OPTS:--Xmx512m}"
      JAVA_TOOL_OPTIONS: "${JAVA_OPTS:--Xmx512m}"
    expose:
      - "8080"
      - "8090"

  scheduler:
    image: "nicolaidam/feedback-scheduler:prod"
    restart: unless-stopped
    environment:
      PORT: "8080"
      MANAGEMENT_SERVER_PORT: "8091"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
      SPRING_LIQUIBASE_ENABLED: "${SPRING_LIQUIBASE_ENABLED:-true}"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD:-}"
      FIREBASE_API_KEY: "${FIREBASE_API_KEY:-}"
      FIREBASE_CONFIG_PATH: "${FIREBASE_CONFIG_PATH:-}"
      ZOHO_ACCOUNT_ID: "${ZOHO_ACCOUNT_ID:-}"
      ZOHO_FOLDER_ID: "${ZOHO_FOLDER_ID:-}"
      ZOHO_MAILBOX_ADDRESS: "${ZOHO_MAILBOX_ADDRESS:-}"
      ZOHO_OAUTH_REFRESH_TOKEN: "${ZOHO_OAUTH_REFRESH_TOKEN:-}"
      ZOHO_CLIENT_ID: "${ZOHO_CLIENT_ID:-}"
      ZOHO_CLIENT_SECRET: "${ZOHO_CLIENT_SECRET:-}"
      JAVA_OPTS: "${JAVA_OPTS:--Xmx512m}"
      JAVA_TOOL_OPTIONS: "${JAVA_OPTS:--Xmx512m}"
    expose:
      - "8080"
      - "8091"

  web:
    image: "nicolaidam/feedback-web:prod"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3000"
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_LETSGROW_EARLY_ACCESS_URL: ${NEXT_PUBLIC_LETSGROW_EARLY_ACCESS_URL:-}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY:-}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:-}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID:-}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID:-}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:-}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:-}
    depends_on:
      - api
    expose:
      - "3000"
