spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
          jwk-set-url: ""
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
server:
  port: 8080

feedback:
  features:
    security:
      enabled: false
    bootstrap:
      enabled: false
  firebase-api-key: "openapi"
  firebase-config-path: "/tmp/firebase-config.json"
