spring:
  main:
    lazy-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
          jwk-set-url: ""
  liquibase:
    enabled: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      initialization-fail-timeout: 0
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
server:
  port: 0
management:
  server:
    port: -1
  endpoints:
    enabled-by-default: false

feedback:
  features:
    security:
      enabled: false
    bootstrap:
      enabled: false
  firebase-api-key: "openapi"
  firebase-config-path: "/tmp/firebase-config.json"
