server:
  port: 8080
  shutdown: graceful
  max-http-request-header-size: 16KB
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
spring:
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
  exposed:
    show-sql: false
    generate-ddl: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:devDb;MODE=PostgreSQL;DATABASE_TO_UPPER=false}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:''}
  h2:
    console:
      enabled: true
      path: /h2-console
feedback:
  firebase-api-key: ${FIREBASE_API_KEY}
  firebase-config-path: ${FIREBASE_CONFIG_PATH}
  mail:
    host: ${IMAP_HOST:}
    port: ${IMAP_PORT:993}
    username: ${IMAP_USERNAME:}
    password: ${IMAP_PASSWORD:}
    folder: ${IMAP_FOLDER:INBOX}
