spring:
  main:
    lazy-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
          jwk-set-url: ""
  liquibase:
    enabled: false
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      initialization-fail-timeout: 0
springdoc:
  api-docs:
    enabled: ${SPRING_DOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRING_DOC_SWAGGER_UI_ENABLED:true}
server:
  port: 8080
management:
  server:
    port: -1
  endpoints:
    enabled-by-default: false

feedback:
  firebase-api-key: "openapi"
  firebase-service-account-json-b64: ""
