server:
  port: ${PORT:8080}
  shutdown: graceful
  max-http-request-header-size: 16KB
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:${PORT:8090}}
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
spring:
  application:
    name: feedback-api
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-url: ${JWK_SET_URL}
          issuer-uri: ${JWT_ISSUER_URI}
  liquibase:
    enabled: true
  exposed:
    show-sql: ${SHOW_EXPOSED_SQL:false}
    generate-ddl: false
springdoc:
  api-docs:
    enabled: ${SPRING_DOC_API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SPRING_DOC_SWAGGER_UI_ENABLED:false}
    path: /
  default-produces-media-type: application/json
feedback:
  firebase-api-key: ${FIREBASE_API_KEY}
  firebase-service-account-json-b64: ${FIREBASE_SERVICE_ACCOUNT_JSON_B64:}
logging:
  include-application-name: true
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    dk.example.feedback: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
