name: Build and Push Docker Image with Jib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Docker image with Jib
      run: ./gradlew jib --image=nicolaidam/feedback:1.0.32
      env:
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

