name: Build and Push Docker Image with Jib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create config directory
      run: mkdir -p config

    - name: Decode and write Firebase Config to a file in config directory
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" > config/firebase_config.json

    - name: Verify config directory and file
      run: ls -la config && cat config/firebase_config.json
    # 5. Authenticate Docker Hub
    #- name: Authenticate Docker Hub
    #  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Build Docker image with Jib
      run: ./gradlew jib --image=nicolaidam/feedback:1.0.22
      env:
        JIB_EXTRA_DIRECTORIES_PATH: "${{ github.workspace }}/config"
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        FIREBASE_CONFIG_PATH: "config/firebase_config.json"

