name: Build and Push Docker Image with Jib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create and prepare config directory
      run: |
        mkdir -p src/main/jib/config
        echo "${{ secrets.FIREBASE_CONFIG }}" | base64 -d > src/main/jib/config/firebase_config.json

    - name: Validate Firebase config (optional debugging)
      run: |
        echo "Decoded Firebase Config Debug Output:"
        cat src/main/jib/config/firebase_config.json | jq .
        
    - name: Build Docker image with Jib
      run: ./gradlew jib --image=nicolaidam/feedback:1.0.28
      env:
        JIB_EXTRA_DIRECTORIES_PATH: "${{ github.workspace }}/config"
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        FIREBASE_CONFIG_PATH: "/config/firebase_config.json"
        SPRING_DATASOURCE_URL: "${{ secrets.SPRING_DATASOURCE_URL }}"
        SPRING_DATASOURCE_USERNAME: "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
        SPRING_DATASOURCE_PASSWORD: "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
        FIREBASE_CONFIG: "${{ secrets.FIREBASE_CONFIG }}"

