name: Generate OpenAPI & Docker Image

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version increment (major, minor, patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  packages: write

jobs:
  release-openapi-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest version tag
        id: get-version
        run: |
          git fetch --tags
          CURRENT_VERSION=$(git tag --sort=-version:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Latest detected version: $CURRENT_VERSION"

      - name: Increment version based on user input
        id: calculate-version
        run: |
          VERSION_TYPE=${{ github.event.inputs.version_type }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT_VERSION }}"
          case "$VERSION_TYPE" in
            patch) PATCH=$((PATCH + 1)) ;;
            minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
            major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
          esac
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version to release: $NEW_VERSION"

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Update OpenAPI and sync with feedback-openapi repo
        env:
          VERSION: ${{ env.NEW_VERSION }}
        run: |
          ./gradlew :api:generateOpenApiDocs -Pversion=${{ env.NEW_VERSION }}

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone feedback-openapi repository
          git clone https://x-access-token:${{ secrets.FEEDBACK_OPENAPI_PAT }}@github.com/FeedbackFriends/feedback-openapi.git feedback-openapi

          # Ensure OpenAPI spec is updated before committing
          cp "$(pwd)/apps/api/build/openapi.yaml" feedback-openapi/openapi.yaml

          cd feedback-openapi

          # Stage file for commit
          git add openapi.yaml
          git status

          # Commit and push changes
          git commit -m "Update OpenAPI spec for version ${{ env.NEW_VERSION }}"
          git push origin main

          # Tag the version and push it
          git tag -a ${{ env.NEW_VERSION }} -m "Generated OpenAPI spec for version ${{ env.NEW_VERSION }}"
          git push origin ${{ env.NEW_VERSION }}

      - name: Build and publish Docker image with Jib
        run: |
          ./gradlew :api:jib --image=nicolaidam/feedback-api:${{ env.NEW_VERSION }}
          ./gradlew :scheduler:jib --image=nicolaidam/feedback-scheduler:${{ env.NEW_VERSION }}
        env:
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Tag and release new API version
        run: |
          COMMIT_URL="https://github.com/FeedbackFriends/feedback-openapi/releases/tag/${{ env.NEW_VERSION }}"
          git tag -a ${{ env.NEW_VERSION }} -m "$COMMIT_URL"
          git push origin ${{ env.NEW_VERSION }}
