name: CI ✅

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Test and build
        run: |
          ./gradlew clean build
