name: Deploy API and Scheduler

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Release Tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG="${{ inputs.tag }}"
          else
            TAG="${{ github.event.release.tag_name }}"
          fi

          echo "Deploying tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Deploy to Debian server using password
        run: |
          echo "Deploying tag ${{ env.TAG }} to Debian server"

          sshpass -p "${{ secrets.DEBIAN_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.DEBIAN_USER }}@${{ secrets.DEBIAN_IP }} << EOF
          set -e

          cd /home/debian/config  # Navigate to Docker Compose directory

          echo "Setting API_TAG and SCHEDULER_TAG..."
          echo "DEPLOY_TAG=${{ env.TAG }}" | sudo tee /home/debian/config/.env > /dev/null

          docker image prune -af
          
          echo "Pulling new images..."
          docker compose pull

          echo "Starting new containers..."
          docker compose up -d --remove-orphans

          echo "Cleaning up old images..."
          docker image prune -f

          echo "Deployment of version ${{ env.TAG }} completed!"
          EOF
