name: Generate OpenAPI Spec and Build Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the tag (e.g., v1.0.0)'
        required: true

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set input version as VERSION
        id: set-version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Check if tag already exists
        id: check-tag
        run: |
          if git rev-parse "refs/tags/${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists."
            exit 1
          fi
        env:
          VERSION: "${{ env.VERSION }}"

      - name: Create new tag
        id: create-tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
        env:
          VERSION: "${{ env.VERSION }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate OpenAPI spec
        run: ./gradlew generateOpenApiDocs -Pversion=${{ env.VERSION }}
        env:
          VERSION: "${{ env.VERSION }}"

      - name: Print OpenAPI YAML file content
        run: cat build/openapi.yaml

      - name: Build Docker image with Jib
        run: ./gradlew jib --image=nicolaidam/feedback:${{ env.VERSION }}
        env:
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
